homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: homeassistant
  password: ahVoh5Uli3ecei8quoQuoophaenuSih1ooch9eivi1uloopoh7uGh6aqu4jeecie
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
devices:
  '0x04cd15fffeb15bd7':
    friendly_name: led_strip-kjøkken_gr1_u-namron
    transition: 0
    state_action: true
  '0xb4e3f9fffe254fe9':
    friendly_name: led_strip-kjøkken_gr2_I-namron
    transition: 0
    state_action: true
  '0xb4e3f9fffe255213':
    friendly_name: led_strip_kjøkken_gr_3_II-namron
    transition: 0
    state_action: true
  '0x847127fffe7840b5':
    friendly_name: dimmerkontroller-kjøkken_vinduer-namron
    state_action: true
    transition: 0
  '0x60a423fffe659aff':
    friendly_name: lysbryter-kjøkken_gr1-namron
  '0x60a423fffe659365':
    friendly_name: lysbryter-kjøkken_gr2-namron
  '0x00158d00027c2599':
    friendly_name: ringeklokke-carport-aqara
  '0x0017880108fd0675':
    friendly_name: smartplugg_linneas-rom_philipshue
  '0x0015bc0031006ac4':
    friendly_name: røykdetektor-linneas_rom-develco
  '0x0015bc003100668e':
    friendly_name: røykvarsler_loftstue-develco
  '0x0015bc0031005d3e':
    friendly_name: røykvarsler-tv_stue-develco
  '0x0015bc003100ee00':
    friendly_name: røykdetektor_kjøkken_develco
  '0x04cf8cdf3c79dfe6':
    friendly_name: smartplugg_bygglys_stue-aqara
    state_action: true
    power_precision: 1
    energy_precision: 1
    voltage_precision: 1
    current_precision: 1
  '0x001788010b00493f':
    friendly_name: switc-inwall_lf-soverom_-philipshue
  '0x1fff000200000053':
    friendly_name: termostat-gulvvarme_kjøkken-namron
    thermostat_unit: celsius
    power_precision: ''
    current_precision: 1
  '0x1fff0002000001ae':
    friendly_name: termostat-gulvvarme_gang-namron
  '0x0015bc003101cebd':
    friendly_name: røykdetektor_utleie_develco
  '0x001788010bd21060':
    friendly_name: bevegelsesensor-innkjoring-phue
  '0x3fff0008000002bb':
    friendly_name: panelovn-lf_soverom-namron
  '0x3fff000800000243':
    friendly_name: panelovn-vaskerom-namron
  '0x3fff00090000021d':
    friendly_name: panelovn-loftstue-namron
  '0x3fff000800000413':
    friendly_name: panelovn-linneas_rom-namron
  '0x84ba20fffed407e1':
    friendly_name: taklampe-linneas_rom-namron
    transition: 3
    color_sync: true
    state_action: true
  '0x3fff00080000027e':
    friendly_name: panelovn-johannes_rom-namron
  '0x5c0272fffe578bd1':
    friendly_name: taklampe-vaskerom-namron
    color_sync: true
    state_action: true
  '0xa4c138a02f79559a':
    friendly_name: bevegelsesensor-kontoret-namron
  '0xa4c138810c5370aa':
    friendly_name: multisensor-utebod_grå-namron
  '0xa4c138c14a1f8293':
    friendly_name: multisensor-baderom-namron
  '0x70ac08fffe706015':
    friendly_name: smartplugg_grå-bod-varmeovn-namron
    power_precision: 1
    energy_precision: 1
    current_precision: 1
    voltage_precision: 1
  '0x00158d0005226255':
    friendly_name: dørsensor-vindfang_gang-aqara
  '0x00158d00045cf2a6':
    friendly_name: dørsensor-baderom-aqara
  '0x0017880106f7d45e':
    friendly_name: bevegelsesensor-kjokken-philipshue
    temperature_precision: 1
  '0x00158d000423ba0c':
    friendly_name: bevegelsesensor-trappe_e1_e2-aqara
  '0x00158d00042c00ae':
    friendly_name: dørsensor-vaskerom_veranda-aqara
  '0xa4c138a5fca96a71':
    friendly_name: multisensor-vaskerom-namron
    temperature_precision: 1
    humidity_precision: 1
  '0x0017880108b6139b':
    friendly_name: '0x0017880108b6139b'
  '0xa4c138888c829029':
    friendly_name: mmwave-kjøkken-bevegelse-tuya
  '0x001788010c342fa4':
    friendly_name: '0x001788010c342fa4'
  '0x040d84fffe436c98':
    friendly_name: led_strip-kjøkken_benkbelysning-namron
  '0xa4c138098ab5bab7':
    friendly_name: dørsensor-lf_soverom-namron
  '0xa4c1381e98ea20e0':
    friendly_name: multisensor-lf_soverom-namron
    temperature_precision: 1
    humidity_precision: 1
  '0xa4c1389c44561131':
    friendly_name: dørsensor-kjokken_vinskap-namron
  '0xa4c138beaae7a0c8':
    friendly_name: multisensor-kjokken-namron
  '0xa4c1389784259931':
    friendly_name: multisensor-williams_rom-namron
  '0xa4c1387fc9d6af7d':
    friendly_name: dørsensor-teknisk_rom_vinskap-namron
  '0xa4c138d3f96cd922':
    friendly_name: dorsensor_utebod_gra-namron
  '0x00158d00090d65e2':
    friendly_name: dørsensor-linneas_rom-aqara
  '0x00158d00052271a7':
    friendly_name: dørsensor-teknisk_rom-aqara
  '0x00158d00091ca932':
    friendly_name: dørsensor-williams_rom-aqara
  '0xa4c1388c59d24e4c':
    friendly_name: dørsensor-loftstue_takvindu-namron
  '0xa4c13893cdc9a08c':
    friendly_name: multisensor-loftstue-namron
  '0xa4c138f51ec641a7':
    friendly_name: multisensor-linneas_rom-namron
    temperature_precision: 1
    humidity_precision: 1
  '0xa4c1384f49930fc8':
    friendly_name: multisensor-tv_stue-namron
  '0xf4b3b1fffe2a8fb5':
    friendly_name: temp-dimmer-stue
    state_action: true
  '0xa4c13845dc34ffbd':
    friendly_name: multisensor-johannes_rom-namron
  '0xa4c1380f77ace70e':
    friendly_name: dørsensor-kontor-namron
  '0xa4c138d1072685b2':
    friendly_name: dørsensor-stue_skyvedør-namron
advanced:
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601_local
permit_join: true
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
